yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  'babel-preset-react-app@*':
    dependencies:
      '@babel/plugin-proposal-private-property-in-object': '^7.0.0'
  '@emotion/react@*':
    peerDependencies:
      '@emotion/babel-plugin': '^11.0.0'
  '@emotion/styled@*':
    peerDependencies:
      '@emotion/babel-plugin': '^11.0.0'
